#!/usr/bin/env bash

# instalar herramientas de sistema
yum update -y
yum install -y git

# instalar servidor web
yum install -y nginx

# clonar el proyecto
git clone https://github.com/tello2004/teczi /tmp/teczi
cp -R /tmp/teczi/html/** /usr/share/nginx/html/

# configurar URL del backend
sed -i 's/"~"/"http:\/\/${backend_host}:5000"/g' /usr/share/nginx/html/app.js

systemctl enable --now nginx
